In [1]:
import numpy as np
import pandas as pd

In [3]:
# two matrics
array1 = np.array([[1, 9, 3],[3, 7, 5]])
array2 = np.array([[3,-9],[5, 4],[6, -8]])
print(array1)
print(array2)

[[1 9 3]
 [3 7 5]]
[[ 3 -9]
 [ 5  4]
 [ 6 -8]]


In [5]:
# randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.93792098 0.86637638 0.5787382  0.52257004]
 [0.19013809 0.32781215 0.30076412 0.09511918]
 [0.07612381 0.1814396  0.10370431 0.05865114]]


In [6]:
mul = np.dot(array1, array2)
print(mul)

[[ 66   3]
 [ 74 -39]]


In [8]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[66, 3], [74, -39]]


In [9]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

4.666666666666667


In [10]:
main_data = pd.read_csv("mtcars.csv")

In [11]:
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
